using UnityEngine;
using UnityEngine.UI;
using System.Collections;

namespace KID
{
	/// <summary>
	/// }jt参
	/// ogluBlu甫妗Blu计qB传uX
	/// </summary>
	public class FireSystem : MonoBehaviour
	{
        #region 逆
        [Header("lu")]
        public GameObject goBullet;
        [Header("诞")]
        public AudioClip soundFire;
        [Header("代刚家ΑGㄏノオ龄}j")]
        public bool modeTest = true;
        [Header("lu计q")]
        public int countBulletCurrent = 1;
        public int countBulletTotal = 10;
        public Text textCountBullet;
        [Header("lut"), Range(0, 5000)]
        public float speedBullet = 1200;

        private AudioSource aud;
        /// <summary>
        /// ネΘlu旄m
        /// </summary>
        private Transform traFirePoint;
        #endregion

        #region ㄆン
        private void Start()
        {
            aud = GetComponent<AudioSource>();
            traFirePoint = transform.Find("ネΘlu旄m");
            UpdateCountBulletUI();
        }

        private void Update()
        {
            #region 代刚跋
            if (modeTest)
            {
                if (Input.GetKeyDown(KeyCode.Mouse0))
                {
                    Fire();
                }

                if (Input.GetKeyDown(KeyCode.R))
                {
                    Reload();
                }
            }
            #endregion
        }
        #endregion

        #region よk
        /// <summary>
        /// }jt参
        /// </summary>
        public void Fire()
        {
            if (countBulletCurrent > 0)
            {
                countBulletCurrent--;
                aud.PlayOneShot(soundFire, Random.Range(0.7f, 1.2f));
                GameObject temp = Instantiate(goBullet, traFirePoint.position, Quaternion.Euler(90, 0, 0));
                temp.GetComponent<Rigidbody>().AddForce(traFirePoint.forward * speedBullet);
                UpdateCountBulletUI();
            }
        }

        /// <summary>
        /// 传uXt参
        /// </summary>
        public void Reload()
        {
            if (countBulletCurrent == 0 && countBulletTotal > 0)
            {
                countBulletTotal--;
                countBulletCurrent++;
                UpdateCountBulletUI();
            }
        }

        /// <summary>
        /// 蠓slu计qざ
        /// </summary>
        private void UpdateCountBulletUI()
        {
            textCountBullet.text = $"{countBulletCurrent} / {countBulletTotal}";
        }
        #endregion
    }
}