using UnityEngine;
using UnityEngine.UI;

namespace KID
{
    public class ScoreManager : MonoBehaviour
    {
        /// <summary>
        /// v瘸踏jb|A代刚L 0.47
        /// </summary>
        [Header("v瘸踏jb|"), Range(0, 3)]
        public float radiusSphereBig = 0.47f;
        [Header("ㄏノ代刚y砰代刚だ计")]
        public bool testScoreBySphere = true;
        [Header("代刚y砰")]
        public Transform testSphere;
        [Header("だ计GネΘだ计ンノ鳘ン")]
        public Transform traScore;
        [Header("だ计ン")]
        public GameObject goScore;
        [Header("建鞫b")]
        public Scrollbar barVertical;

        public static ScoreManager instance;

        private int index;

        private void Awake()
        {
            instance = this;
        }

        private void OnDrawGizmos()
        {
            Gizmos.color = new Color(0, 1, 0, 0.3f);
            Gizmos.DrawSphere(transform.position, radiusSphereBig);
        }

        private void Update()
        {
            if (testScoreBySphere) CheckBulletPositionAndScore(testSphere);
        }

        /// <summary>
        /// 浪dluy夹Hの赣oだ
        /// </summary>
        /// <param name="bullet">lu跑韦弗</param>
        public void CheckBulletPositionAndScore(Transform bullet)
        {
            Vector3 posBullet = bullet.position;
            posBullet.z = transform.position.z;

            float dis = Vector3.Distance(transform.position, posBullet);
            print("PいみIZ瞒G" + dis);

            float score = 10 - dis / radiusSphereBig * 10;
            print("だ计G" + score);
            score = score > 0 ? score : 0;

            GameObject tempScore = Instantiate(goScore, traScore.transform);
            barVertical.value = 0;

            index++;
            Text text = tempScore.transform.Find("s腹Pだ计").GetComponent<Text>();
            text.text = $"s腹 {index.ToString("00")} | だ计G {score.ToString("00")}";
        }
    }
}